mysql_settings: &mysql_settings
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: kumo
  socket: /cloudsql/red-agora-py:us-central1:red-agora
  database: agora

development:
  <<: *mysql_settings

production:
  <<: *mysql_settings

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
