postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: 104.155.157.246
  database: agora

development:
  <<: *postgresql_settings

production:
  <<: *postgresql_settings

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
