postgresql_settings: &postgresql_settings
  adapter: mysql2
  encoding: unicode
  pool: 5
  username: root
  password: kumo
  host: 35.184.252.104
  database: agora

development:
  <<: *postgresql_settings

production:
  <<: *postgresql_settings

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
